-- ============================================================
-- M03 Ventas Online — desinstalación
--
-- Elimina únicamente lo perteneciente a Sales:
--   - el schema sales completo (las siete tablas, sus triggers,
--     la función sales.set_updated_at() y sales.__migrations)
--
-- Conserva intactos:
--   - CORE (schema core, colaciones core.es_ci y core.es_search)
--   - M01 Catálogo (schema catalog)
--   - M04 Clientes (schema crm)
--   - cualquier objeto de otro módulo
--   - las extensiones compartidas: M03 no instala ninguna y no
--     retira las que otros módulos pusieron
--
-- Las dos claves foráneas cruzadas —sales.orders hacia
-- crm.customers y sales.order_lines hacia catalog.product_items—
-- se van con las tablas que las llevan, porque viven en el lado
-- dependiente. Ni crm ni catalog quedan tocados: esa es la razón
-- de declararlas en la migración de M03 y no en las suyas.
--
-- DROP SCHEMA ... CASCADE elimina las tablas, sus triggers, la
-- función del schema y el historial de migraciones.
--
-- Idempotente: IF EXISTS permite ejecutarlo dos veces seguidas.
-- ============================================================

DROP SCHEMA IF EXISTS sales CASCADE;
