// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sillar.Core.Data;

#nullable disable

namespace Sillar.Core.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260816073536_CoreInitial")]
    partial class CoreInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("Npgsql:CollationDefinition:core.es_ci", "es-PE-u-ks-level2,es-PE-u-ks-level2,icu,False")
                .HasAnnotation("Npgsql:CollationDefinition:core.es_search", "es-PE-u-ks-level1,es-PE-u-ks-level1,icu,False")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sillar.Core.Domain.AdminSession", b =>
                {
                    b.Property<Guid>("AdminSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_session_id");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_user_id");

                    b.Property<string>("CsrfTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("csrf_token_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_agent");

                    b.HasKey("AdminSessionId")
                        .HasName("pk_admin_sessions");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("idx_admin_sessions_user");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_admin_sessions_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_admin_sessions_token_hash");

                    b.ToTable("admin_sessions", "core", t =>
                        {
                            t.HasCheckConstraint("ck_admin_sessions_csrf_token_hash_not_empty", "btrim(csrf_token_hash) <> ''");

                            t.HasCheckConstraint("ck_admin_sessions_token_hash_not_empty", "btrim(token_hash) <> ''");
                        });
                });

            modelBuilder.Entity("Sillar.Core.Domain.AdminUser", b =>
                {
                    b.Property<int>("AdminUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("admin_user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("AdminUserId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("AdminUserId")
                        .HasName("pk_admin_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_admin_users_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_admin_users_is_active");

                    b.ToTable("admin_users", "core", t =>
                        {
                            t.HasCheckConstraint("ck_admin_users_email_not_empty", "btrim(email) <> ''");

                            t.HasCheckConstraint("ck_admin_users_failed_login_count", "failed_login_count >= 0");

                            t.HasCheckConstraint("ck_admin_users_full_name_not_empty", "btrim(full_name) <> ''");

                            t.HasCheckConstraint("ck_admin_users_password_hash_not_empty", "btrim(password_hash) <> ''");

                            t.HasCheckConstraint("ck_admin_users_role", "role IN ('super_admin', 'admin', 'editor')");
                        });
                });

            modelBuilder.Entity("Sillar.Core.Domain.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action");

                    b.Property<string>("AdminUserEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("admin_user_email");

                    b.Property<int?>("AdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_user_id");

                    b.Property<string>("EntityId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("ModuleCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("module_code");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Summary")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("summary");

                    b.HasKey("AuditLogId")
                        .HasName("pk_audit_log");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("idx_audit_log_admin_user_id");

                    b.HasIndex("ModuleCode")
                        .HasDatabaseName("idx_audit_log_module_code");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_audit_log_occurred_at");

                    b.ToTable("audit_log", "core", t =>
                        {
                            t.HasCheckConstraint("ck_audit_log_action", "action IN ('create', 'update', 'delete', 'activate', 'deactivate', 'login', 'login_failed', 'logout', 'setup')");
                        });
                });

            modelBuilder.Entity("Sillar.Core.Domain.Installation", b =>
                {
                    b.Property<int>("InstallationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("installation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("InstallationId"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("business_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("InstallationKey")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_key");

                    b.Property<bool>("IsSetupComplete")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_setup_complete");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("license_type");

                    b.Property<DateTimeOffset?>("LicensedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("licensed_until");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("product_version");

                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("singleton");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("InstallationId")
                        .HasName("pk_installation");

                    b.HasIndex("InstallationKey")
                        .IsUnique()
                        .HasDatabaseName("uq_installation_installation_key");

                    b.HasIndex("Singleton")
                        .IsUnique()
                        .HasDatabaseName("uq_installation_singleton");

                    b.ToTable("installation", "core", t =>
                        {
                            t.HasCheckConstraint("ck_installation_business_name_not_empty", "btrim(business_name) <> ''");

                            t.HasCheckConstraint("ck_installation_license_type", "license_type IN ('trial', 'subscription', 'perpetual')");

                            t.HasCheckConstraint("ck_installation_product_version_not_empty", "btrim(product_version) <> ''");

                            t.HasCheckConstraint("ck_installation_singleton", "singleton");
                        });
                });

            modelBuilder.Entity("Sillar.Core.Domain.MediaAsset", b =>
                {
                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("AltText")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("alt_text");

                    b.Property<string>("Checksum")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOrphan")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_orphan");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_name");

                    b.Property<string>("OwnerModuleCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("owner_module_code");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("relative_path");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoredName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("stored_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("MediaAssetId")
                        .HasName("pk_media_assets");

                    b.HasIndex("Checksum")
                        .HasDatabaseName("idx_media_assets_checksum");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("idx_media_assets_created_by");

                    b.HasIndex("OwnerModuleCode")
                        .HasDatabaseName("idx_media_assets_owner_module_code");

                    b.HasIndex("StoredName")
                        .IsUnique()
                        .HasDatabaseName("uq_media_assets_stored_name");

                    b.ToTable("media_assets", "core", t =>
                        {
                            t.HasCheckConstraint("ck_media_assets_mime_type_not_empty", "btrim(mime_type) <> ''");

                            t.HasCheckConstraint("ck_media_assets_relative_path_not_empty", "btrim(relative_path) <> ''");

                            t.HasCheckConstraint("ck_media_assets_size_bytes", "size_bytes > 0");

                            t.HasCheckConstraint("ck_media_assets_stored_name_not_empty", "btrim(stored_name) <> ''");
                        });
                });

            modelBuilder.Entity("Sillar.Core.Domain.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("module_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsCore")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_core");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("ModuleId")
                        .HasName("pk_modules");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_modules_code");

                    b.ToTable("modules", "core", t =>
                        {
                            t.HasCheckConstraint("ck_modules_code_format", "code ~ '^[a-z][a-z0-9_]{1,39}$'");

                            t.HasCheckConstraint("ck_modules_code_not_empty", "btrim(code) <> ''");

                            t.HasCheckConstraint("ck_modules_description_not_empty", "btrim(description) <> ''");

                            t.HasCheckConstraint("ck_modules_display_name_not_empty", "btrim(display_name) <> ''");

                            t.HasCheckConstraint("ck_modules_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_modules_version_not_empty", "btrim(version) <> ''");
                        });
                });

            modelBuilder.Entity("Sillar.Core.Domain.ModuleActivation", b =>
                {
                    b.Property<int>("ModuleActivationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("module_activation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ModuleActivationId"));

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("activated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deactivated_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("module_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ModuleActivationId")
                        .HasName("pk_module_activations");

                    b.HasIndex("ModuleId")
                        .IsUnique()
                        .HasDatabaseName("uq_module_activations_module_id");

                    b.ToTable("module_activations", "core");
                });

            modelBuilder.Entity("Sillar.Core.Domain.ModuleDependency", b =>
                {
                    b.Property<int>("ModuleDependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("module_dependency_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ModuleDependencyId"));

                    b.Property<int>("DependsOnModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("depends_on_module_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("kind");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("module_id");

                    b.HasKey("ModuleDependencyId")
                        .HasName("pk_module_dependencies");

                    b.HasIndex("DependsOnModuleId")
                        .HasDatabaseName("idx_module_dependencies_depends_on_module_id");

                    b.HasIndex("ModuleId", "DependsOnModuleId")
                        .IsUnique()
                        .HasDatabaseName("uq_module_dependencies_module_depends_on");

                    b.ToTable("module_dependencies", "core", t =>
                        {
                            t.HasCheckConstraint("ck_module_dependencies_kind", "kind IN ('hard', 'soft')");

                            t.HasCheckConstraint("ck_module_dependencies_no_self", "module_id <> depends_on_module_id");
                        });
                });

            modelBuilder.Entity("Sillar.Core.Domain.SiteSetting", b =>
                {
                    b.Property<int>("SiteSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("site_setting_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("SiteSettingId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("setting_key");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("setting_value");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("value_type");

                    b.HasKey("SiteSettingId")
                        .HasName("pk_site_settings");

                    b.HasIndex("SettingKey")
                        .IsUnique()
                        .HasDatabaseName("uq_site_settings_setting_key");

                    b.ToTable("site_settings", "core", t =>
                        {
                            t.HasCheckConstraint("ck_site_settings_key_not_empty", "btrim(setting_key) <> ''");

                            t.HasCheckConstraint("ck_site_settings_value_type", "value_type IN ('text', 'number', 'boolean', 'url', 'email', 'json')");
                        });
                });

            modelBuilder.Entity("Sillar.Core.Domain.AdminSession", b =>
                {
                    b.HasOne("Sillar.Core.Domain.AdminUser", "AdminUser")
                        .WithMany("Sessions")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_sessions_admin_user_id");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("Sillar.Core.Domain.AuditLog", b =>
                {
                    b.HasOne("Sillar.Core.Domain.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_log_admin_user_id");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("Sillar.Core.Domain.MediaAsset", b =>
                {
                    b.HasOne("Sillar.Core.Domain.AdminUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_media_assets_created_by");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Sillar.Core.Domain.ModuleActivation", b =>
                {
                    b.HasOne("Sillar.Core.Domain.Module", "Module")
                        .WithOne("Activation")
                        .HasForeignKey("Sillar.Core.Domain.ModuleActivation", "ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_module_activations_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Sillar.Core.Domain.ModuleDependency", b =>
                {
                    b.HasOne("Sillar.Core.Domain.Module", "DependsOnModule")
                        .WithMany("Dependents")
                        .HasForeignKey("DependsOnModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_module_dependencies_depends_on_module_id");

                    b.HasOne("Sillar.Core.Domain.Module", "Module")
                        .WithMany("Dependencies")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_module_dependencies_module_id");

                    b.Navigation("DependsOnModule");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Sillar.Core.Domain.AdminUser", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Sillar.Core.Domain.Module", b =>
                {
                    b.Navigation("Activation");

                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");
                });
#pragma warning restore 612, 618
        }
    }
}
