// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sillar.Modules.Tracking.Data;

#nullable disable

namespace Sillar.Modules.Tracking.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20261007212800_TrackingInitial")]
    partial class TrackingInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tracking")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sillar.Modules.Tracking.Domain.OrderTracking", b =>
                {
                    b.Property<Guid>("OrderTrackingId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_tracking_id");

                    b.Property<int?>("BoardPriority")
                        .HasColumnType("integer")
                        .HasColumnName("board_priority");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("InternalDueAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("internal_due_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastTouchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_touched_at");

                    b.Property<string>("LastTouchedByAdminUserHomeNode")
                        .HasColumnType("text")
                        .HasColumnName("last_touched_by_admin_user_home_node");

                    b.Property<int?>("LastTouchedByAdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("last_touched_by_admin_user_id");

                    b.Property<string>("LastTouchedByName")
                        .HasColumnType("text")
                        .HasColumnName("last_touched_by_name");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<bool>("Pinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pinned");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("OrderTrackingId")
                        .HasName("pk_order_tracking");

                    b.HasIndex("ServiceOrderId")
                        .IsUnique()
                        .HasDatabaseName("uq_order_tracking_service_order_id");

                    b.ToTable("order_tracking", "tracking", t =>
                        {
                            t.HasCheckConstraint("ck_order_tracking_last_touched_not_fictitious", "last_touched_by_name IS NULL OR btrim(last_touched_by_name) <> 'Sistema'");

                            t.HasCheckConstraint("ck_order_tracking_last_touched_triple", "((last_touched_by_name IS NULL AND last_touched_by_admin_user_id IS NULL AND last_touched_by_admin_user_home_node IS NULL) OR (last_touched_by_name IS NOT NULL AND last_touched_by_admin_user_id IS NOT NULL AND last_touched_by_admin_user_home_node IS NOT NULL))");

                            t.HasCheckConstraint("ck_order_tracking_last_touched_values", "last_touched_by_name IS NULL OR (btrim(last_touched_by_name) <> '' AND last_touched_by_admin_user_id > 0 AND btrim(last_touched_by_admin_user_home_node) <> '')");

                            t.HasCheckConstraint("ck_order_tracking_priority", "board_priority IS NULL OR board_priority >= 0");

                            t.HasCheckConstraint("ck_order_tracking_replication", "btrim(origin_node) <> '' AND row_version > 0");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Tracking.Domain.TrackingNote", b =>
                {
                    b.Property<Guid>("TrackingNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracking_note_id");

                    b.Property<string>("AuthorAdminUserHomeNode")
                        .HasColumnType("text")
                        .HasColumnName("author_admin_user_home_node");

                    b.Property<int?>("AuthorAdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("author_admin_user_id");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text")
                        .HasColumnName("author_name");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrderTrackingId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_tracking_id");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TrackingNoteId")
                        .HasName("pk_tracking_notes");

                    b.HasIndex("OrderTrackingId", "CreatedAt")
                        .HasDatabaseName("idx_tracking_notes_order_created");

                    b.ToTable("tracking_notes", "tracking", t =>
                        {
                            t.HasCheckConstraint("ck_tracking_notes_author_not_fictitious", "author_name IS NULL OR btrim(author_name) <> 'Sistema'");

                            t.HasCheckConstraint("ck_tracking_notes_author_triple", "((author_name IS NULL AND author_admin_user_id IS NULL AND author_admin_user_home_node IS NULL) OR (author_name IS NOT NULL AND author_admin_user_id IS NOT NULL AND author_admin_user_home_node IS NOT NULL))");

                            t.HasCheckConstraint("ck_tracking_notes_author_values", "author_name IS NULL OR (btrim(author_name) <> '' AND author_admin_user_id > 0 AND btrim(author_admin_user_home_node) <> '')");

                            t.HasCheckConstraint("ck_tracking_notes_body", "btrim(body) <> ''");

                            t.HasCheckConstraint("ck_tracking_notes_replication", "btrim(origin_node) <> '' AND row_version > 0");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Tracking.Domain.TrackingNote", b =>
                {
                    b.HasOne("Sillar.Modules.Tracking.Domain.OrderTracking", "OrderTracking")
                        .WithMany("Notes")
                        .HasForeignKey("OrderTrackingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tracking_notes_order_tracking_id");

                    b.Navigation("OrderTracking");
                });

            modelBuilder.Entity("Sillar.Modules.Tracking.Domain.OrderTracking", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
