// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sillar.Modules.Sales.Data;

#nullable disable

namespace Sillar.Modules.Sales.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    partial class SalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sillar.Modules.Sales.Domain.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cart_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("CartId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CartId")
                        .HasName("pk_carts");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("uq_carts_customer_id");

                    b.ToTable("carts", "sales");
                });

            modelBuilder.Entity("Sillar.Modules.Sales.Domain.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cart_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("integer")
                        .HasColumnName("cart_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CartItemId")
                        .HasName("pk_cart_items");

                    b.HasIndex("CartId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("uq_cart_items_cart_id_item_id");

                    b.ToTable("cart_items", "sales", t =>
                        {
                            t.HasCheckConstraint("ck_cart_items_quantity_positiva", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Sales.Domain.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomerDocumentNumber")
                        .HasColumnType("text")
                        .HasColumnName("customer_document_number");

                    b.Property<string>("CustomerDocumentType")
                        .HasColumnType("text")
                        .HasColumnName("customer_document_type");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerFullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_full_name");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("text")
                        .HasColumnName("customer_phone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_code");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<DateTimeOffset>("PaymentDueAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("payment_due_at");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("OrderId")
                        .HasName("pk_orders");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_orders_customer_id");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("uq_orders_order_code");

                    b.HasIndex("PaymentDueAt")
                        .HasDatabaseName("idx_orders_payment_due_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_orders_status");

                    b.ToTable("orders", "sales", t =>
                        {
                            t.HasCheckConstraint("ck_orders_customer_email_no_vacio", "btrim(customer_email) <> ''");

                            t.HasCheckConstraint("ck_orders_customer_full_name_no_vacio", "btrim(customer_full_name) <> ''");

                            t.HasCheckConstraint("ck_orders_order_code_no_vacio", "btrim(order_code) <> ''");

                            t.HasCheckConstraint("ck_orders_status", "status IN ('pending_payment', 'payment_to_verify', 'preparing', 'ready_for_pickup', 'delivered', 'expired', 'cancelled')");

                            t.HasCheckConstraint("ck_orders_total_amount_no_negativo", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Sales.Domain.OrderLine", b =>
                {
                    b.Property<Guid>("OrderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_line_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("SaleUnit")
                        .HasColumnType("text")
                        .HasColumnName("sale_unit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VariantValue")
                        .HasColumnType("text")
                        .HasColumnName("variant_value");

                    b.HasKey("OrderLineId")
                        .HasName("pk_order_lines");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("idx_order_lines_item_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_order_lines_order_id");

                    b.ToTable("order_lines", "sales", t =>
                        {
                            t.HasCheckConstraint("ck_order_lines_product_name_no_vacio", "btrim(product_name) <> ''");

                            t.HasCheckConstraint("ck_order_lines_quantity_positiva", "quantity > 0");

                            t.HasCheckConstraint("ck_order_lines_unit_price_no_negativo", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Sales.Domain.OrderPayment", b =>
                {
                    b.Property<Guid>("OrderPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_payment_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("registered_at");

                    b.Property<string>("RegisteredBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registered_by");

                    b.Property<string>("RegisteredByAdminUserHomeNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registered_by_admin_user_home_node");

                    b.Property<int>("RegisteredByAdminUserLocalId")
                        .HasColumnType("integer")
                        .HasColumnName("registered_by_admin_user_local_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("WasLate")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("was_late");

                    b.HasKey("OrderPaymentId")
                        .HasName("pk_order_payments");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_order_payments_order_id");

                    b.HasIndex("WasLate")
                        .HasDatabaseName("idx_order_payments_was_late")
                        .HasFilter("was_late");

                    b.ToTable("order_payments", "sales", t =>
                        {
                            t.HasCheckConstraint("ck_order_payments_amount_no_negativo", "amount >= 0");

                            t.HasCheckConstraint("ck_order_payments_atribucion_home_node_no_vacio", "btrim(registered_by_admin_user_home_node) <> ''");

                            t.HasCheckConstraint("ck_order_payments_atribucion_local_positiva", "registered_by_admin_user_local_id > 0");

                            t.HasCheckConstraint("ck_order_payments_method", "method IN ('yape', 'efectivo')");

                            t.HasCheckConstraint("ck_order_payments_registered_by_no_vacio", "btrim(registered_by) <> ''");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Sales.Domain.OrderSeries", b =>
                {
                    b.Property<int>("OrderSeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("order_series_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("OrderSeriesId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_number");

                    b.Property<string>("NodeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("node_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("OrderSeriesId")
                        .HasName("pk_order_series");

                    b.HasIndex("NodeCode", "Year")
                        .IsUnique()
                        .HasDatabaseName("uq_order_series_node_code_year");

                    b.ToTable("order_series", "sales", t =>
                        {
                            t.HasCheckConstraint("ck_order_series_last_number_no_negativo", "last_number >= 0");

                            t.HasCheckConstraint("ck_order_series_node_code_no_vacio", "btrim(node_code) <> ''");

                            t.HasCheckConstraint("ck_order_series_year_razonable", "year BETWEEN 2000 AND 9999");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Sales.Domain.OrderStatusChange", b =>
                {
                    b.Property<Guid>("OrderStatusChangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_status_change_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("text")
                        .HasColumnName("changed_by");

                    b.Property<string>("ChangedByAdminUserHomeNode")
                        .HasColumnType("text")
                        .HasColumnName("changed_by_admin_user_home_node");

                    b.Property<int?>("ChangedByAdminUserLocalId")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_admin_user_local_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text")
                        .HasColumnName("from_status");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("OrderStatusChangeId")
                        .HasName("pk_order_status_changes");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_order_status_changes_order_id");

                    b.ToTable("order_status_changes", "sales", t =>
                        {
                            t.HasCheckConstraint("ck_order_status_changes_atribucion_completa", "(changed_by IS NULL AND changed_by_admin_user_local_id IS NULL   AND changed_by_admin_user_home_node IS NULL) OR (changed_by IS NOT NULL AND changed_by_admin_user_local_id IS NOT NULL   AND changed_by_admin_user_home_node IS NOT NULL)");

                            t.HasCheckConstraint("ck_order_status_changes_atribucion_home_node_no_vacio", "changed_by_admin_user_home_node IS NULL OR btrim(changed_by_admin_user_home_node) <> ''");

                            t.HasCheckConstraint("ck_order_status_changes_atribucion_local_positiva", "changed_by_admin_user_local_id IS NULL OR changed_by_admin_user_local_id > 0");

                            t.HasCheckConstraint("ck_order_status_changes_changed_by_no_vacio", "changed_by IS NULL OR btrim(changed_by) <> ''");

                            t.HasCheckConstraint("ck_order_status_changes_from_status", "from_status IS NULL OR from_status IN ('pending_payment', 'payment_to_verify', 'preparing', 'ready_for_pickup', 'delivered', 'expired', 'cancelled')");

                            t.HasCheckConstraint("ck_order_status_changes_no_es_el_mismo", "from_status IS NULL OR from_status <> to_status");

                            t.HasCheckConstraint("ck_order_status_changes_to_status", "to_status IN ('pending_payment', 'payment_to_verify', 'preparing', 'ready_for_pickup', 'delivered', 'expired', 'cancelled')");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Sales.Domain.CartItem", b =>
                {
                    b.HasOne("Sillar.Modules.Sales.Domain.Cart", null)
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_items_cart_id");
                });

            modelBuilder.Entity("Sillar.Modules.Sales.Domain.OrderLine", b =>
                {
                    b.HasOne("Sillar.Modules.Sales.Domain.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_lines_order_id");
                });

            modelBuilder.Entity("Sillar.Modules.Sales.Domain.OrderPayment", b =>
                {
                    b.HasOne("Sillar.Modules.Sales.Domain.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_payments_order_id");
                });

            modelBuilder.Entity("Sillar.Modules.Sales.Domain.OrderStatusChange", b =>
                {
                    b.HasOne("Sillar.Modules.Sales.Domain.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_status_changes_order_id");
                });
#pragma warning restore 612, 618
        }
    }
}
