// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sillar.Modules.Crm.Data;

#nullable disable

namespace Sillar.Modules.Crm.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crm")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sillar.Modules.Crm.Domain.ContactMessage", b =>
                {
                    b.Property<int>("ContactMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("contact_message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ContactMessageId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ContactMessageId")
                        .HasName("pk_contact_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_contact_messages_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_contact_messages_customer");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_contact_messages_active")
                        .HasFilter("is_active");

                    b.ToTable("contact_messages", "crm", t =>
                        {
                            t.HasCheckConstraint("ck_contact_messages_contact_channel", "(email IS NOT NULL OR phone IS NOT NULL)");

                            t.HasCheckConstraint("ck_contact_messages_email_no_vacio", "email IS NULL OR btrim(email) <> ''");

                            t.HasCheckConstraint("ck_contact_messages_full_name_no_vacio", "btrim(full_name) <> ''");

                            t.HasCheckConstraint("ck_contact_messages_message_no_vacio", "btrim(message) <> ''");

                            t.HasCheckConstraint("ck_contact_messages_phone_no_vacio", "phone IS NULL OR btrim(phone) <> ''");

                            t.HasCheckConstraint("ck_contact_messages_subject_no_vacio", "subject IS NULL OR btrim(subject) <> ''");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Crm.Domain.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("BlockedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("blocked_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text")
                        .HasColumnName("document_type");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("text")
                        .HasColumnName("internal_notes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("ReactivationRequestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reactivation_requested_at");

                    b.Property<DateTimeOffset?>("ReactivationResolvedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reactivation_resolved_at");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CustomerId")
                        .HasName("pk_customers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_customers_email");

                    b.HasIndex("DocumentType", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_customers_document")
                        .HasFilter("document_number IS NOT NULL");

                    b.ToTable("customers", "crm", t =>
                        {
                            t.HasCheckConstraint("ck_customers_document_number_no_vacio", "document_number IS NULL OR btrim(document_number) <> ''");

                            t.HasCheckConstraint("ck_customers_document_pair", "(document_type IS NULL AND document_number IS NULL) OR (document_type IS NOT NULL AND document_number IS NOT NULL)");

                            t.HasCheckConstraint("ck_customers_document_type", "document_type IS NULL OR document_type IN ('dni', 'ruc')");

                            t.HasCheckConstraint("ck_customers_email_no_vacio", "btrim(email) <> ''");

                            t.HasCheckConstraint("ck_customers_full_name_no_vacio", "btrim(full_name) <> ''");

                            t.HasCheckConstraint("ck_customers_lifecycle_state", "(\n    is_active = true\n    AND deactivated_at IS NULL\n    AND blocked_at IS NULL\n)\nOR\n(\n    is_active = false\n    AND deactivated_at IS NOT NULL\n    AND blocked_at IS NULL\n)\nOR\n(\n    is_active = false\n    AND deactivated_at IS NULL\n    AND blocked_at IS NOT NULL\n)");

                            t.HasCheckConstraint("ck_customers_reactivation_timestamps", "reactivation_resolved_at IS NULL\nOR (\n    reactivation_requested_at IS NOT NULL\n    AND reactivation_resolved_at >= reactivation_requested_at\n)");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Crm.Domain.CustomerAccount", b =>
                {
                    b.Property<int>("CustomerAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customer_account_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("CustomerAccountId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CustomerAccountId")
                        .HasName("pk_customer_accounts");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("uq_customer_accounts_customer_id");

                    b.ToTable("customer_accounts", "crm", t =>
                        {
                            t.HasCheckConstraint("ck_customer_accounts_password_hash_no_vacio", "btrim(password_hash) <> ''");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Crm.Domain.CustomerAddress", b =>
                {
                    b.Property<Guid>("CustomerAddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_address_id");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("District")
                        .HasColumnType("text")
                        .HasColumnName("district");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_preferred");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<string>("Province")
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CustomerAddressId")
                        .HasName("pk_customer_addresses");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("uq_customer_addresses_preferred")
                        .HasFilter("is_preferred AND is_active");

                    b.ToTable("customer_addresses", "crm", t =>
                        {
                            t.HasCheckConstraint("ck_customer_addresses_address_line_no_vacio", "btrim(address_line) <> ''");

                            t.HasCheckConstraint("ck_customer_addresses_preferred_active", "NOT is_preferred OR is_active");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Crm.Domain.CustomerSession", b =>
                {
                    b.Property<int>("CustomerSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customer_session_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("CustomerSessionId"));

                    b.Property<string>("CsrfTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("csrf_token_hash");

                    b.Property<int>("CustomerAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_account_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("CustomerSessionId")
                        .HasName("pk_customer_sessions");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_customer_sessions_token_hash");

                    b.ToTable("customer_sessions", "crm", t =>
                        {
                            t.HasCheckConstraint("ck_customer_sessions_csrf_token_hash_no_vacio", "btrim(csrf_token_hash) <> ''");

                            t.HasCheckConstraint("ck_customer_sessions_expires_after_issued", "expires_at > issued_at");

                            t.HasCheckConstraint("ck_customer_sessions_last_seen_after_issued", "last_seen_at >= issued_at");

                            t.HasCheckConstraint("ck_customer_sessions_revoked_after_issued", "revoked_at IS NULL OR revoked_at >= issued_at");

                            t.HasCheckConstraint("ck_customer_sessions_token_hash_no_vacio", "btrim(token_hash) <> ''");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Crm.Domain.CustomerToken", b =>
                {
                    b.Property<int>("CustomerTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customer_token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("CustomerTokenId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("used_at");

                    b.HasKey("CustomerTokenId")
                        .HasName("pk_customer_tokens");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_customer_tokens_token_hash");

                    b.ToTable("customer_tokens", "crm", t =>
                        {
                            t.HasCheckConstraint("ck_customer_tokens_expires_after_created", "expires_at > created_at");

                            t.HasCheckConstraint("ck_customer_tokens_purpose", "purpose IN (\n    'invitation',\n    'email_verification',\n    'password_reset'\n)");

                            t.HasCheckConstraint("ck_customer_tokens_token_hash_no_vacio", "btrim(token_hash) <> ''");

                            t.HasCheckConstraint("ck_customer_tokens_used_after_created", "used_at IS NULL OR used_at >= created_at");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Crm.Domain.ContactMessage", b =>
                {
                    b.HasOne("Sillar.Modules.Crm.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_contact_messages_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Sillar.Modules.Crm.Domain.CustomerAccount", b =>
                {
                    b.HasOne("Sillar.Modules.Crm.Domain.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_accounts_customer_id");
                });

            modelBuilder.Entity("Sillar.Modules.Crm.Domain.CustomerAddress", b =>
                {
                    b.HasOne("Sillar.Modules.Crm.Domain.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_addresses_customer_id");
                });

            modelBuilder.Entity("Sillar.Modules.Crm.Domain.CustomerSession", b =>
                {
                    b.HasOne("Sillar.Modules.Crm.Domain.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_sessions_customer_account_id");
                });

            modelBuilder.Entity("Sillar.Modules.Crm.Domain.CustomerToken", b =>
                {
                    b.HasOne("Sillar.Modules.Crm.Domain.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_tokens_customer_id");
                });
#pragma warning restore 612, 618
        }
    }
}
