// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sillar.Modules.B2B.Data;

#nullable disable

namespace Sillar.Modules.B2B.Migrations
{
    [DbContext(typeof(B2bDbContext))]
    [Migration("20261004225318_B2bInitial")]
    partial class B2bInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("b2b")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sillar.Modules.B2B.Domain.InstitutionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("institution_request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text")
                        .HasColumnName("contact_person");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("InstitutionDocument")
                        .HasColumnType("text")
                        .HasColumnName("institution_document");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("institution_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("StaffNotes")
                        .HasColumnType("text")
                        .HasColumnName("staff_notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("recibida")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_institution_requests");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_institution_requests_customer");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_institution_requests_status");

                    b.ToTable("institution_requests", "b2b", t =>
                        {
                            t.HasCheckConstraint("ck_institution_requests_description", "btrim(description) <> ''");

                            t.HasCheckConstraint("ck_institution_requests_institution_name", "btrim(institution_name) <> ''");

                            t.HasCheckConstraint("ck_institution_requests_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_institution_requests_status", "status IN ('recibida', 'en_revision', 'cotizada', 'cerrada', 'rechazada')");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.B2B.Domain.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("quote_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int?>("InstitutionRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_request_id");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("invalidated_at");

                    b.Property<string>("InvalidatedReason")
                        .HasColumnType("text")
                        .HasColumnName("invalidated_reason");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaidRegisteredBy")
                        .HasColumnType("text")
                        .HasColumnName("paid_registered_by");

                    b.Property<string>("PaidRegisteredByAdminUserHomeNode")
                        .HasColumnType("text")
                        .HasColumnName("paid_registered_by_admin_user_home_node");

                    b.Property<int?>("PaidRegisteredByAdminUserLocalId")
                        .HasColumnType("integer")
                        .HasColumnName("paid_registered_by_admin_user_local_id");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text")
                        .HasColumnName("payment_reference");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_number");

                    b.Property<int?>("SpecialOrderLeadId")
                        .HasColumnType("integer")
                        .HasColumnName("special_order_lead_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("borrador")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_quotes_customer");

                    b.HasIndex("InstitutionRequestId");

                    b.HasIndex("QuoteNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_quotes_number");

                    b.HasIndex("SpecialOrderLeadId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_quotes_status");

                    b.ToTable("quotes", "b2b", t =>
                        {
                            t.HasCheckConstraint("ck_quotes_atribucion_completa", "(paid_registered_by IS NULL AND paid_registered_by_admin_user_local_id IS NULL   AND paid_registered_by_admin_user_home_node IS NULL) OR (paid_registered_by IS NOT NULL AND paid_registered_by_admin_user_local_id IS NOT NULL   AND paid_registered_by_admin_user_home_node IS NOT NULL)");

                            t.HasCheckConstraint("ck_quotes_atribucion_home_node", "paid_registered_by_admin_user_home_node IS NULL OR btrim(paid_registered_by_admin_user_home_node) <> ''");

                            t.HasCheckConstraint("ck_quotes_atribucion_local_positiva", "paid_registered_by_admin_user_local_id IS NULL OR paid_registered_by_admin_user_local_id > 0");

                            t.HasCheckConstraint("ck_quotes_atribucion_nombre", "paid_registered_by IS NULL OR btrim(paid_registered_by) <> ''");

                            t.HasCheckConstraint("ck_quotes_number", "btrim(quote_number) <> ''");

                            t.HasCheckConstraint("ck_quotes_origen", "(special_order_lead_id IS NULL) <> (institution_request_id IS NULL)");

                            t.HasCheckConstraint("ck_quotes_pago_tiene_atribucion", "paid_at IS NULL OR paid_registered_by IS NOT NULL");

                            t.HasCheckConstraint("ck_quotes_payment_method", "payment_method IS NULL OR payment_method IN ('yape', 'efectivo', 'tarjeta')");

                            t.HasCheckConstraint("ck_quotes_status", "status IN ('borrador', 'enviada', 'aprobada', 'pagada', 'anulada')");

                            t.HasCheckConstraint("ck_quotes_total_amount", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.B2B.Domain.QuoteLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("quote_line_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CatalogPriceAtQuote")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("catalog_price_at_quote");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("ProductName")
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("QuoteId")
                        .HasColumnType("integer")
                        .HasColumnName("quote_id");

                    b.Property<string>("SaleUnit")
                        .HasColumnType("text")
                        .HasColumnName("sale_unit");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.Property<string>("VariantValue")
                        .HasColumnType("text")
                        .HasColumnName("variant_value");

                    b.HasKey("Id")
                        .HasName("pk_quote_lines");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("idx_quote_lines_item");

                    b.HasIndex("QuoteId")
                        .HasDatabaseName("idx_quote_lines_quote");

                    b.ToTable("quote_lines", "b2b", t =>
                        {
                            t.HasCheckConstraint("ck_quote_lines_catalog_price", "catalog_price_at_quote IS NULL OR catalog_price_at_quote >= 0");

                            t.HasCheckConstraint("ck_quote_lines_description", "btrim(description) <> ''");

                            t.HasCheckConstraint("ck_quote_lines_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_quote_lines_snapshot", "(item_id IS NOT NULL OR (product_name IS NULL AND variant_value IS NULL AND sale_unit IS NULL AND catalog_price_at_quote IS NULL)) AND (item_id IS NULL OR (product_name IS NOT NULL AND btrim(product_name) <> ''))");

                            t.HasCheckConstraint("ck_quote_lines_sort_order", "sort_order >= 0");

                            t.HasCheckConstraint("ck_quote_lines_unit_price", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.B2B.Domain.QuoteNumberSeries", b =>
                {
                    b.Property<string>("SeriesCode")
                        .HasColumnType("text")
                        .HasColumnName("series_code");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<int>("LastValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_value");

                    b.HasKey("SeriesCode", "Year")
                        .HasName("pk_quote_number_series");

                    b.ToTable("quote_number_series", "b2b", t =>
                        {
                            t.HasCheckConstraint("ck_quote_number_series_last_value", "last_value >= 0");

                            t.HasCheckConstraint("ck_quote_number_series_series_code", "series_code ~ '^[A-Z]$'");

                            t.HasCheckConstraint("ck_quote_number_series_year", "year BETWEEN 2000 AND 9999");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.B2B.Domain.SpecialOrderLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("special_order_lead_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateOnly?>("NeededBy")
                        .HasColumnType("date")
                        .HasColumnName("needed_by");

                    b.Property<bool>("PendingRelink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pending_relink");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_slug");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("StaffNotes")
                        .HasColumnType("text")
                        .HasColumnName("staff_notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("recibida")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_special_order_leads");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_special_order_leads_customer");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_special_order_leads_product");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_special_order_leads_status");

                    b.ToTable("special_order_leads", "b2b", t =>
                        {
                            t.HasCheckConstraint("ck_special_order_leads_description", "btrim(description) <> ''");

                            t.HasCheckConstraint("ck_special_order_leads_product_name", "btrim(product_name) <> ''");

                            t.HasCheckConstraint("ck_special_order_leads_product_slug", "btrim(product_slug) <> ''");

                            t.HasCheckConstraint("ck_special_order_leads_quantity", "quantity IS NULL OR quantity > 0");

                            t.HasCheckConstraint("ck_special_order_leads_status", "status IN ('recibida', 'en_revision', 'cotizada', 'cerrada', 'rechazada')");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.B2B.Domain.Quote", b =>
                {
                    b.HasOne("Sillar.Modules.B2B.Domain.InstitutionRequest", null)
                        .WithMany()
                        .HasForeignKey("InstitutionRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_quotes_institution_request");

                    b.HasOne("Sillar.Modules.B2B.Domain.SpecialOrderLead", null)
                        .WithMany()
                        .HasForeignKey("SpecialOrderLeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_quotes_special_order_lead");
                });

            modelBuilder.Entity("Sillar.Modules.B2B.Domain.QuoteLine", b =>
                {
                    b.HasOne("Sillar.Modules.B2B.Domain.Quote", null)
                        .WithMany("Lines")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_lines_quote");
                });

            modelBuilder.Entity("Sillar.Modules.B2B.Domain.Quote", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
