<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Sillar.Shared\Sillar.Shared.csproj" />
    <ProjectReference Include="..\Sillar.Shared.Data\Sillar.Shared.Data.csproj" />
    <ProjectReference Include="..\Sillar.Core.Contracts\Sillar.Core.Contracts.csproj" />
    <ProjectReference Include="..\Sillar.Modules.Services.Contracts\Sillar.Modules.Services.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup><PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" /></ItemGroup>
  <ItemGroup><InternalsVisibleTo Include="Sillar.Modules.Services.Tests" /></ItemGroup>
</Project>
