// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sillar.Modules.ServiceOrders.Data;

#nullable disable

namespace Sillar.Modules.ServiceOrders.Migrations
{
    [DbContext(typeof(ServiceOrdersDbContext))]
    partial class ServiceOrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("service_orders")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sillar.Modules.ServiceOrders.Domain.ServiceOrder", b =>
                {
                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedByAdminName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_admin_name");

                    b.Property<string>("CreatedByAdminUserHomeNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_admin_user_home_node");

                    b.Property<int>("CreatedByAdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_admin_user_id");

                    b.Property<string>("CurrentAssigneeAdminUserHomeNode")
                        .HasColumnType("text")
                        .HasColumnName("current_assignee_admin_user_home_node");

                    b.Property<int?>("CurrentAssigneeAdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("current_assignee_admin_user_id");

                    b.Property<string>("CurrentAssigneeName")
                        .HasColumnType("text")
                        .HasColumnName("current_assignee_name");

                    b.Property<string>("CustomerEmailSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("customer_email_snapshot");

                    b.Property<Guid>("CreateIdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("create_idempotency_key");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name_snapshot");

                    b.Property<string>("CustomerPhoneSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("customer_phone_snapshot");

                    b.Property<DateTimeOffset>("LastStatusChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_status_changed_at");

                    b.Property<string>("LastStatusChangedByAdminUserHomeNode")
                        .HasColumnType("text")
                        .HasColumnName("last_status_changed_by_admin_user_home_node");

                    b.Property<int?>("LastStatusChangedByAdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("last_status_changed_by_admin_user_id");

                    b.Property<string>("LastStatusChangedByName")
                        .HasColumnType("text")
                        .HasColumnName("last_status_changed_by_name");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<DateTimeOffset?>("PromisedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("promised_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<string>("ReceivedNotes")
                        .HasColumnType("text")
                        .HasColumnName("received_notes");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasDefaultValue("received")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VisibleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visible_code");

                    b.HasKey("ServiceOrderId")
                        .HasName("pk_service_orders");

                    b.HasIndex("CreateIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_service_orders_create_idempotency_key");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("idx_service_orders_received_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_service_orders_status");

                    b.HasIndex("VisibleCode")
                        .IsUnique()
                        .HasDatabaseName("uq_service_orders_visible_code");

                    b.ToTable("service_orders", "service_orders", t =>
                        {
                            t.HasCheckConstraint("ck_service_orders_assignee_triple", "((current_assignee_name IS NULL AND current_assignee_admin_user_id IS NULL AND current_assignee_admin_user_home_node IS NULL) OR (current_assignee_name IS NOT NULL AND current_assignee_admin_user_id IS NOT NULL AND current_assignee_admin_user_home_node IS NOT NULL))");

                            t.HasCheckConstraint("ck_service_orders_assignee_values", "current_assignee_name IS NULL OR (btrim(current_assignee_name) <> '' AND current_assignee_admin_user_id > 0 AND btrim(current_assignee_admin_user_home_node) <> '')");

                            t.HasCheckConstraint("ck_service_orders_contact", "nullif(btrim(customer_phone_snapshot), '') IS NOT NULL OR nullif(btrim(customer_email_snapshot), '') IS NOT NULL");

                            t.HasCheckConstraint("ck_service_orders_create_idempotency_key", "create_idempotency_key <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_service_orders_created_by", "btrim(created_by_admin_name) <> '' AND created_by_admin_user_id > 0 AND btrim(created_by_admin_user_home_node) <> ''");

                            t.HasCheckConstraint("ck_service_orders_customer_name", "btrim(customer_name_snapshot) <> ''");

                            t.HasCheckConstraint("ck_service_orders_email", "customer_email_snapshot IS NULL OR btrim(customer_email_snapshot) <> ''");

                            t.HasCheckConstraint("ck_service_orders_last_actor_triple", "((last_status_changed_by_name IS NULL AND last_status_changed_by_admin_user_id IS NULL AND last_status_changed_by_admin_user_home_node IS NULL) OR (last_status_changed_by_name IS NOT NULL AND last_status_changed_by_admin_user_id IS NOT NULL AND last_status_changed_by_admin_user_home_node IS NOT NULL))");

                            t.HasCheckConstraint("ck_service_orders_last_actor_values", "last_status_changed_by_name IS NULL OR (btrim(last_status_changed_by_name) <> '' AND last_status_changed_by_admin_user_id > 0 AND btrim(last_status_changed_by_admin_user_home_node) <> '')");

                            t.HasCheckConstraint("ck_service_orders_last_actor_not_fictitious", "last_status_changed_by_name IS NULL OR btrim(last_status_changed_by_name) <> 'Sistema'");

                            t.HasCheckConstraint("ck_service_orders_last_status_at", "last_status_changed_at >= received_at");

                            t.HasCheckConstraint("ck_service_orders_phone", "customer_phone_snapshot IS NULL OR btrim(customer_phone_snapshot) <> ''");

                            t.HasCheckConstraint("ck_service_orders_promised_at", "promised_at IS NULL OR promised_at >= received_at");

                            t.HasCheckConstraint("ck_service_orders_replication", "btrim(origin_node) <> '' AND row_version > 0");

                            t.HasCheckConstraint("ck_service_orders_status", "status IN ('received', 'in_progress', 'ready', 'completed', 'cancelled')");

                            t.HasCheckConstraint("ck_service_orders_visible_code", "btrim(visible_code) <> ''");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.ServiceOrders.Domain.ServiceOrderAssignmentEvent", b =>
                {
                    b.Property<Guid>("AssignmentEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_event_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("AssigneeAdminUserHomeNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assignee_admin_user_home_node");

                    b.Property<int>("AssigneeAdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("assignee_admin_user_id");

                    b.Property<string>("AssigneeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assignee_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<string>("PerformedByAdminUserHomeNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("performed_by_admin_user_home_node");

                    b.Property<int>("PerformedByAdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_admin_user_id");

                    b.Property<string>("PerformedByName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("performed_by_name");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("AssignmentEventId")
                        .HasName("pk_service_order_assignment_events");

                    b.HasIndex("ServiceOrderId", "OccurredAt")
                        .HasDatabaseName("idx_service_order_assignment_events_order_occurred");

                    b.ToTable("service_order_assignment_events", "service_orders", t =>
                        {
                            t.HasCheckConstraint("ck_service_order_assignment_events_action", "action IN ('assigned','unassigned')");

                            t.HasCheckConstraint("ck_service_order_assignment_events_actor", "btrim(performed_by_name) <> '' AND performed_by_admin_user_id > 0 AND btrim(performed_by_admin_user_home_node) <> ''");

                            t.HasCheckConstraint("ck_service_order_assignment_events_assignee", "btrim(assignee_name) <> '' AND assignee_admin_user_id > 0 AND btrim(assignee_admin_user_home_node) <> ''");

                            t.HasCheckConstraint("ck_service_order_assignment_events_replication", "btrim(origin_node) <> '' AND row_version > 0");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.ServiceOrders.Domain.ServiceOrderItem", b =>
                {
                    b.Property<Guid>("ServiceOrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_item_id");

                    b.Property<decimal?>("AgreedUnitPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("agreed_unit_price");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ImageAltTextSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("image_alt_text_snapshot");

                    b.Property<string>("ImageUrlSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("image_url_snapshot");

                    b.Property<Guid?>("MediaAssetIdSnapshot")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id_snapshot");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("RequestedDetails")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_details");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("SaleUnitSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("sale_unit_snapshot");

                    b.Property<string>("ServiceDescriptionSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("service_description_snapshot");

                    b.Property<string>("ServiceNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name_snapshot");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<string>("ServiceShortDescriptionSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("service_short_description_snapshot");

                    b.Property<string>("ServiceSlugSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_slug_snapshot");

                    b.Property<int>("ServiceSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_source_id");

                    b.Property<string>("ServiceSourceNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_source_node");

                    b.Property<decimal?>("ShowcasePriceSnapshot")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("showcase_price_snapshot");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ServiceOrderItemId")
                        .HasName("pk_service_order_items");

                    b.HasIndex("ServiceOrderId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("uq_service_order_items_order_sort");

                    b.ToTable("service_order_items", "service_orders", t =>
                        {
                            t.HasCheckConstraint("ck_service_order_items_agreed_price", "agreed_unit_price IS NULL OR agreed_unit_price >= 0");

                            t.HasCheckConstraint("ck_service_order_items_description", "service_short_description_snapshot IS NOT NULL OR service_description_snapshot IS NOT NULL");

                            t.HasCheckConstraint("ck_service_order_items_image_alt", "media_asset_id_snapshot IS NULL OR nullif(btrim(image_alt_text_snapshot), '') IS NOT NULL");

                            t.HasCheckConstraint("ck_service_order_items_name", "btrim(service_name_snapshot) <> ''");

                            t.HasCheckConstraint("ck_service_order_items_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_service_order_items_replication", "btrim(origin_node) <> '' AND row_version > 0");

                            t.HasCheckConstraint("ck_service_order_items_requested_details", "btrim(requested_details) <> ''");

                            t.HasCheckConstraint("ck_service_order_items_showcase_price", "showcase_price_snapshot IS NULL OR showcase_price_snapshot >= 0");

                            t.HasCheckConstraint("ck_service_order_items_slug", "service_slug_snapshot COLLATE \"C\" ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("ck_service_order_items_sort_order", "sort_order >= 0");

                            t.HasCheckConstraint("ck_service_order_items_source_id", "service_source_id > 0");

                            t.HasCheckConstraint("ck_service_order_items_source_node", "btrim(service_source_node) <> ''");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.ServiceOrders.Domain.ServiceOrderSeries", b =>
                {
                    b.Property<int>("ServiceOrderSeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("service_order_series_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ServiceOrderSeriesId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_number");

                    b.Property<string>("NodeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("node_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("ServiceOrderSeriesId")
                        .HasName("pk_service_order_series");

                    b.HasIndex("NodeCode", "Year")
                        .IsUnique()
                        .HasDatabaseName("uq_service_order_series_node_code_year");

                    b.ToTable("service_order_series", "service_orders", t =>
                        {
                            t.HasCheckConstraint("ck_service_order_series_last_number", "last_number >= 0");

                            t.HasCheckConstraint("ck_service_order_series_node_code", "btrim(node_code) <> ''");


                            t.HasCheckConstraint("ck_service_order_series_year", "year BETWEEN 2000 AND 9999");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.ServiceOrders.Domain.ServiceOrderStatusHistory", b =>
                {
                    b.Property<Guid>("StatusHistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_history_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text")
                        .HasColumnName("from_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<string>("PerformedByAdminUserHomeNode")
                        .HasColumnType("text")
                        .HasColumnName("performed_by_admin_user_home_node");

                    b.Property<int?>("PerformedByAdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_admin_user_id");

                    b.Property<string>("PerformedByName")
                        .HasColumnType("text")
                        .HasColumnName("performed_by_name");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("StatusHistoryId")
                        .HasName("pk_service_order_status_history");

                    b.HasIndex("ServiceOrderId", "OccurredAt")
                        .HasDatabaseName("idx_service_order_status_history_order_occurred");

                    b.ToTable("service_order_status_history", "service_orders", t =>
                        {
                            t.HasCheckConstraint("ck_service_order_status_history_actor_triple", "((performed_by_name IS NULL AND performed_by_admin_user_id IS NULL AND performed_by_admin_user_home_node IS NULL) OR (performed_by_name IS NOT NULL AND performed_by_admin_user_id IS NOT NULL AND performed_by_admin_user_home_node IS NOT NULL))");

                            t.HasCheckConstraint("ck_service_order_status_history_actor_values", "performed_by_name IS NULL OR (btrim(performed_by_name) <> '' AND performed_by_admin_user_id > 0 AND btrim(performed_by_admin_user_home_node) <> '')");

                            t.HasCheckConstraint("ck_service_order_status_history_actor_not_fictitious", "performed_by_name IS NULL OR btrim(performed_by_name) <> 'Sistema'");

                            t.HasCheckConstraint("ck_service_order_status_history_change", "from_status IS NULL OR from_status <> to_status");

                            t.HasCheckConstraint("ck_service_order_status_history_from", "from_status IS NULL OR from_status IN ('received', 'in_progress', 'ready', 'completed', 'cancelled')");

                            t.HasCheckConstraint("ck_service_order_status_history_initial", "from_status IS NOT NULL OR to_status = 'received'");

                            t.HasCheckConstraint("ck_service_order_status_history_replication", "btrim(origin_node) <> '' AND row_version > 0");

                            t.HasCheckConstraint("ck_service_order_status_history_to", "to_status IN ('received', 'in_progress', 'ready', 'completed', 'cancelled')");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.ServiceOrders.Domain.ServiceOrderAssignmentEvent", b =>
                {
                    b.HasOne("Sillar.Modules.ServiceOrders.Domain.ServiceOrder", "ServiceOrder")
                        .WithMany("AssignmentEvents")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_assignment_events_service_order_id");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("Sillar.Modules.ServiceOrders.Domain.ServiceOrderItem", b =>
                {
                    b.HasOne("Sillar.Modules.ServiceOrders.Domain.ServiceOrder", "ServiceOrder")
                        .WithMany("Items")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_items_service_order_id");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("Sillar.Modules.ServiceOrders.Domain.ServiceOrderStatusHistory", b =>
                {
                    b.HasOne("Sillar.Modules.ServiceOrders.Domain.ServiceOrder", "ServiceOrder")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_status_history_service_order_id");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("Sillar.Modules.ServiceOrders.Domain.ServiceOrder", b =>
                {
                    b.Navigation("AssignmentEvents");

                    b.Navigation("Items");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
