// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sillar.Modules.Catalog.Data;

#nullable disable

namespace Sillar.Modules.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260816073647_CatalogInitial")]
    partial class CatalogInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("LogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("logo_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_brands_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_brands_slug");

                    b.ToTable("brands", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_brands_name_no_vacio", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_brands_slug_formato", "slug COLLATE \"C\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_categories_activas")
                        .HasFilter("is_active");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("idx_categories_parent");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_categories_slug");

                    b.ToTable("categories", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_categories_name_no_vacio", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_categories_parent_no_self", "parent_id IS NULL OR parent_id <> id");

                            t.HasCheckConstraint("ck_categories_slug_formato", "slug COLLATE \"C\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("ck_categories_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<decimal?>("ListPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("list_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<Guid?>("PrimaryCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_category_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("SaleUnit")
                        .HasColumnType("text")
                        .HasColumnName("sale_unit");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VariantLabel")
                        .HasColumnType("text")
                        .HasColumnName("variant_label");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("idx_products_marca");

                    b.HasIndex("PrimaryCategoryId")
                        .HasDatabaseName("idx_products_categoria_principal");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_products_slug");

                    b.HasIndex("IsActive", "IsPublic")
                        .HasDatabaseName("idx_products_publicos")
                        .HasFilter("is_active AND is_public");

                    b.ToTable("products", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_products_list_price_no_negativo", "list_price IS NULL OR list_price >= 0");

                            t.HasCheckConstraint("ck_products_name_no_vacio", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_products_slug_formato", "slug COLLATE \"C\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProductId", "CategoryId")
                        .HasName("pk_product_categories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_product_categories_categoria");

                    b.ToTable("product_categories", "catalog");
                });

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasColumnType("text")
                        .HasColumnName("alt_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_product_images");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("uq_product_images_una_principal")
                        .HasFilter("is_primary");

                    b.HasIndex("ProductId", "MediaAssetId")
                        .IsUnique()
                        .HasDatabaseName("uq_product_images_producto_archivo");

                    b.ToTable("product_images", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_images_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.ProductItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_node");

                    b.Property<decimal?>("PriceOverride")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_override");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VariantValue")
                        .HasColumnType("text")
                        .HasColumnName("variant_value");

                    b.HasKey("Id")
                        .HasName("pk_product_items");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("uq_product_items_barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_product_items_code")
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_product_items_producto");

                    b.HasIndex("ProductId", "VariantValue")
                        .IsUnique()
                        .HasDatabaseName("uq_product_items_valor")
                        .HasFilter("variant_value IS NOT NULL");

                    b.ToTable("product_items", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_items_barcode_no_vacio", "barcode IS NULL OR btrim(barcode) <> ''");

                            t.HasCheckConstraint("ck_product_items_code_no_vacio", "code IS NULL OR btrim(code) <> ''");

                            t.HasCheckConstraint("ck_product_items_price_no_negativo", "price_override IS NULL OR price_override >= 0");

                            t.HasCheckConstraint("ck_product_items_sort_order", "sort_order >= 0");

                            t.HasCheckConstraint("ck_product_items_variant_value_no_vacio", "variant_value IS NULL OR btrim(variant_value) <> ''");
                        });
                });

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.Category", b =>
                {
                    b.HasOne("Sillar.Modules.Catalog.Domain.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.Product", b =>
                {
                    b.HasOne("Sillar.Modules.Catalog.Domain.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_products_brand_id");

                    b.HasOne("Sillar.Modules.Catalog.Domain.Category", "PrimaryCategory")
                        .WithMany()
                        .HasForeignKey("PrimaryCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_products_primary_category_id");

                    b.Navigation("Brand");

                    b.Navigation("PrimaryCategory");
                });

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.ProductCategory", b =>
                {
                    b.HasOne("Sillar.Modules.Catalog.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_categories_category_id");

                    b.HasOne("Sillar.Modules.Catalog.Domain.Product", "Product")
                        .WithMany("Categories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_categories_product_id");

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.ProductImage", b =>
                {
                    b.HasOne("Sillar.Modules.Catalog.Domain.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_images_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.ProductItem", b =>
                {
                    b.HasOne("Sillar.Modules.Catalog.Domain.Product", "Product")
                        .WithMany("Items")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_items_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Sillar.Modules.Catalog.Domain.Product", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Images");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
